server:
  port: 7107
spring:
  application:
    name: eureka-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-client-ribbon
    api-b:
      path: /api-b/**
      serviceId: eureka-feign
